uploads = []

[[generated]]
id = "8yMDPhvmTOfAYxZRlXWif"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LEYXDe0l6lAp9fdYFki6H"
uri = "file://artifacts/mobile/assets/images/facial.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0bR1fJxihXXvvGhf4GCEQ"
uri = "file://artifacts/mobile/assets/images/massage.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kyLyT7R6AgNGCSlsAzIhV"
uri = "file://artifacts/mobile/assets/images/nails.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PV1iGEqyyKzXGPjVHniaq"
uri = "file://artifacts/mobile/assets/images/hair.png"
type = "image"
title = "generated_image"

[[generated]]
id = "glCuigfRt9dNWklxLyUXd"
uri = "file://artifacts/mobile/assets/images/body.png"
type = "image"
title = "generated_image"

[[generated]]
id = "idDgbwfjfPUaLQhL-PFF5"
uri = "file://artifacts/spa-deck/public/illust-spa-hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uGwMBrySX1tl2Qa1n2Nka"
uri = "file://artifacts/spa-deck/public/illust-app.png"
type = "image"
title = "generated_image"

[[generated]]
id = "1YmRPWfrDuDXkDVQFyAvB"
uri = "file://artifacts/spa-deck/public/illust-team.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0Kc5we4usnwNPN9c5OkBh"
uri = "file://artifacts/spa-deck/public/illust-mpesa.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "stLMmPC0ElCQkZXo_Hqd3"
uri = "file://.local/outputs/Beauty-Booker.pptx"
type = "slides"
title = "Beauty Booker.pptx"
